export const categories = [
    'Baby Food', 
    'Baby Formula', 
    "Baby Products",
    'Candy', 
    'Cereal', 
    'Cheese', 
    'Chocolate', 
    'Chips & Snacks', 
    'Coffee',
    'Crackers',
    "Deodorant",
    'Drinks',
    'Energy Drinks',
    "Feminine Hygeine",
    'Frozen Pizza',
    "Household Cleaners",
    'Ice Cream',
    'Juice',
    "Laundry Detergent",
    "Paper Products",
    'Pasta Sauce',
    'Pickles',
    'Sauces & Dressings',
    "Shampoo",
    "Skincare",
    'Supplements',
    "Tea",
    "Toothpaste",
];

export const ownerTypes =[
    'Megacorporation',
    'Private Equity',
    'Founder or Family Owned'
]
